# Setup
title:            The 3D Printing Club
tagline:          'Learning To Create'
description:      'A website for the club of the same name.'
url:              https://odysseusinspace.github.io
baseurl:          '/'
paginate:         5

# About and contact
author:
  name:           'Richard Helper'
  url:            https://www.thingiverse.com/odysseus_in_space/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
